### ISSUE TITLE
Seq iterator has an undefined size, causing it to access elements that don't exist

### ISSUE THREAD

**Issue by neelmehta247** [facebook/immutable-js#1256]
### What happened
```
/Users/neel/Encircle/encircle/client/node_modules/immutable/dist/immutable.js:3238
          return iteratorValue(type, iterations - 1, step.value[1], step);
                                                               ^

TypeError: Cannot read property '1' of undefined
    at Iterator.next (/Users/neel/Encircle/encircle/client/node_modules/immutable/dist/immutable.js:3238:64)
    at Iterator.next (/Users/neel/Encircle/encircle/client/node_modules/immutable/dist/immutable.js:3025:29)
    at Object.<anonymous> (/Users/neel/Encircle/encircle/client/test.js:16:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
```

I was able to minimise this issue down to the following case:
```
Immutable = require('immutable')

var seq = Immutable.Seq([1, 2, 3, 4]);
seq = seq.flatMap(function(elem) {
    return [elem, elem];
}).slice(0, 20).map(function(elem) {
    return true;
});

// At this point seq is an `IndexedIterator` with an undefined size

var iter = seq.values();
var done = false;

while (!done) {
    var next = iter.next();
    done = next.done;
}
```

After a bit of debugging the issue seemed to be that when a `Seq` is sliced it creates an `IndexedIterator` and in the current configuration (a `flatMap` followed by a `slice` followed by a `map`) it causes this `iterator` to not have a size value. Due to this reason, creating an `iterator` on this causes issues as the internals of `Immutable` try to access the value of the next element which doesn't exist.

**Comment by neelmehta247** [comment]
ping: How do I move this forward?

**Comment by neelmehta247** [comment]
@leebyron poke. I would like to get this fixed if possible!

**Comment by leebyron** [comment]
Thanks for highlighting and your patience.

If someone is looking for a way to contribute, a PR investigating and fixing this bug would be helpful
