### ISSUE TITLE
fromJS TypeError: Class constructor KeyedSequence cannot be invoked without 'new'

### ISSUE THREAD

**Issue by erichulburd** [facebook/immutable-js#1272]
### What happened

I installed immutable-js at `"immutable-js": "^0.3.1-6"`.

```
let state = {data: {0: {'eat': {yada: 'yada'}}}, ui: {submitting: false, submissionErrors: { 0: {'eat': {some: 'error'}} }  }};
let Immutable = require('immutable-js');
let iState = Immutable.fromJS(state)
TypeError: Class constructor KeyedSequence cannot be invoked without 'new'
    at fromJSDefault (~/Code/arbol/app-slim/node_modules/immutable-js/dist/immutable.js:1176:18)
    at Object.fromJS (~/Code/arbol/app-slim/node_modules/immutable-js/dist/immutable.js:1156:11)
    at repl:1:16
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
```

I have used `fromJS` in the past without passing in a reviver, and according to the [docs](https://facebook.github.io/immutable-js/docs/#/fromJS) it is still an optional parameter.

Is this now an anti-pattern that Immutable intends to throw an error on? 

### How to reproduce

The code above should be reproducible. Note this also happens when `state = {}`.

**Comment by leebyron** [comment]
Sorry, I haven't been able to reproduce your test.

However you seem to be using https://www.npmjs.com/package/immutable-js which is not the same as this library, https://www.npmjs.com/package/immutable
