### ISSUE TITLE
In Node.js, Record can't have a field named "name"

### ISSUE THREAD

**Issue by nickretallack** [facebook/immutable-js#1516]
Despite [examples in the documentation](https://facebook.github.io/immutable-js/docs/#/Record/getDescriptiveName), if you define a `Record` with a field named `name` it is impossible to instantiate it in Node.js.  You will always see an error.

```bash
$ node --version
v8.4.0
$ node
> const {Record} = require('immutable-js')
undefined
> const A = new Record({name: ''})
undefined
> const a = new A()
Error: Can't call set on an immutable record.
    at invariant (/Users/nick/Documents/GitHub/Turbo/node_modules/immutable-js/dist/immutable.js:182:29)
    at Record.set (/Users/nick/Documents/GitHub/Turbo/node_modules/immutable-js/dist/immutable.js:1360:15)
    at new Record (/Users/nick/Documents/GitHub/Turbo/node_modules/immutable-js/dist/immutable.js:1261:44)
    at repl:1:11
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
```

**Comment by nickretallack** [comment]
Wow.  I am not having a good time with `Record` in Node.

```
$ node
> const {Record, Map} = require('immutable-js')
undefined
> const A = new Record({a:null})
undefined
> const a = new A({a: new Map()})
undefined
> a.a
null
```

**Comment by nickretallack** [comment]
Oh, it's `immutable`, not `immutable-js`.  Whoops.
