### ISSUE TITLE
Random error when using very large Record

### ISSUE THREAD

**Issue by Pauan** [facebook/immutable-js#288]
Using Node.js version 0.10.22, with Immutable-js version 3.6.2, I found an odd bug:

```
var immutablejs = require("immutable");

var obj = {};

for (var i = 0; i < 10000; ++i) {
  obj["foo" + i] = i;
}

var Foo = immutablejs.Record(obj);

var foo = new Foo(obj);

foo.get("foo0");
```

_Sometimes_ when running the above code, I get this error:

```
TypeError: Cannot call method 'hasOwnProperty' of undefined
    at Record.has (/home/pauan/Programming/JavaScript/immutable/node_modules/immutable/dist/immutable.js:3760:34)
    at Record.get (/home/pauan/Programming/JavaScript/immutable/node_modules/immutable/dist/immutable.js:3764:17)
    at repl:1:5
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
```

Other times I don't. It seems to be random whether the error triggers or not.

I'm only able to reproduce this with very large Records (e.g. 10,000 keys). Using 1,000 keys does not trigger the error.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by leebyron** [comment]
Closing this aging issue - sorry I wasn't able to be more helpful. Sounds like a browser limitation for maximum properties on an object
