### ISSUE TITLE
{Set,Map,List}.toString throws when it contains a Symbol

### ISSUE THREAD

**Issue by ivan** [facebook/immutable-js#316]
Running immutable dist/ with io.js:

```
> var Immutable = require('immutable');
undefined
> var x = new Immutable.Set().add(Symbol('hi'))
undefined
> x
TypeError: Cannot convert a Symbol value to a string
    at D:\opt\NodeModules\immutable\dist\immutable.js:4267:55
    at D:\opt\NodeModules\immutable\dist\immutable.js:1131:36
    at D:\opt\NodeModules\immutable\dist\immutable.js:1018:56
    at D:\opt\NodeModules\immutable\dist\immutable.js:3590:58
    at D:\opt\NodeModules\immutable\dist\immutable.js:1864:16
    at ArrayMapNode.iterate.HashCollisionNode.iterate [as iterate] (D:\opt\NodeModules\immutable\dist\immutable.js:2213:11)
    at Map.__iterate (D:\opt\NodeModules\immutable\dist\immutable.js:1862:32)
    at Set.__iterate (D:\opt\NodeModules\immutable\dist\immutable.js:3590:24)
    at ToSetSequence.__iterate (D:\opt\NodeModules\immutable\dist\immutable.js:1018:25)
    at SetIterable.mappedSequence.__iterateUncached (D:\opt\NodeModules\immutable\dist\immutable.js:1130:23)
```

Running immutable src/ with io.js and 6to5:

```
> var Immutable = require('immutable');
undefined
> var x = new Immutable.Set().add(Symbol('hi'))
undefined
> x
TypeError: Cannot convert a Symbol value to a string
    at D:/opt/NodeModules/immutable/src/IterableImpl.js:203:53
    at D:/opt/NodeModules/immutable/src/Operations.js:238:20
    at D:/opt/NodeModules/immutable/src/Operations.js:125:38
    at D:/opt/NodeModules/immutable/src/Set.js:136:42
    at D:/opt/NodeModules/immutable/src/Map.js:168:14
    at ArrayMapNode.iterate.HashCollisionNode.iterate [as iterate] (D:/opt/NodeModules/immutable/src/Map.js:517:9)
    at Map.__iterate (D:/opt/NodeModules/immutable/src/Map.js:166:30)
    at Set.__iterate (D:/opt/NodeModules/immutable/src/Set.js:136:22)
    at ToSetSequence.__iterate (D:/opt/NodeModules/immutable/src/Operations.js:125:23)
    at SetSeq.mappedSequence.__iterateUncached (D:/opt/NodeModules/immutable/src/Operations.js:237:21)
```

The same thing happens in Chrome 40, though you have to do `x.toString()` instead of `x` in the console.

Line 203 is

```javascript
  join(separator) {
    assertNotInfinite(this.size);
    separator = separator !== undefined ? '' + separator : ',';
    var joined = '';
    var isFirst = true;
    this.__iterate(v => {
      isFirst ? (isFirst = false) : (joined += separator);
      joined += v !== null && v !== undefined ? v : '';    ///////////////////
    });
    return joined;
  },
```

**Comment by ivan** [comment]
Changing
`joined += v !== null && v !== undefined ? v : '';`
to
`joined += v !== null && v !== undefined ? String(v) : '';`
seems to fix the problem.

**Comment by leebyron** [comment]
Thanks for the report. I'll get on this
