### ISSUE TITLE
3.6.3 broke build

### ISSUE THREAD

**Issue by steida** [facebook/immutable-js#375]
module.js:340
    throw err;
    ^
Error: Cannot find module 'immutable'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/este/dev/este/src/client/todos/store.js:2:39)

Missing dist

**Comment by steida** [comment]
duplicate
