### ISSUE TITLE
Can't run tests on node 0.12.0

### ISSUE THREAD

**Issue by Gozala** [facebook/immutable-js#412]
All `*.ts` tests fail on node 0.12.0 (at least on my machine) with a pretty similar stack traces:

```sh
> immutable@3.6.4 test /Users/gozala/Projects/immutable-js
> ./resources/node_test.sh

Using Jest CLI v0.4.0
 FAIL  __tests__/ArraySeq.ts
TypeError: /Users/gozala/Projects/immutable-js/resources/jestPreprocessor.js: undefined is not a function
  at BitMatrixImpl.release (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:815:32)
  at PullInstantiatedTypeReferenceSymbol.PullTypeSymbol.wrapsSomeTypeParameterIntoInfinitelyExpandingTypeReference (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:31567:26)
  at PullInstantiatedTypeReferenceSymbol.getGenerativeTypeClassification (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:46402:30)
  at PullTypeEnclosingTypeWalker.getGenerativeClassification (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:32236:36)
  at PullTypeResolutionContext.oneOfClassificationsIsInfinitelyExpanding (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:32867:71)
  at PullTypeResolver.typesAreIdenticalInEnclosingTypes (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:39263:29)
  at PullTypeResolver.signatureTypeParametersParametersAndReturnTypesAreIdentical (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:39504:52)
  at PullTypeResolver.signaturesAreIdenticalWorker (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:39492:75)
  at PullTypeResolver.signaturesAreIdentical (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:39470:40)
  at PullTypeResolver.signatureIsRelatableToTargetWorker (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:40140:22)
  at PullTypeResolver.signatureIsRelatableToTarget (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:40120:36)
  at PullTypeResolver.signatureGroupIsRelatableToTarget (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:40095:61)
  at PullTypeResolver.sourceCallSignaturesAreRelatableToTargetCallSignatures (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:39961:27)
  at PullTypeResolver.sourceIsRelatableToTargetWorker (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:39748:23)
  at PullTypeResolver.sourceIsRelatableToTarget (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:39729:36)
  at PullTypeResolver.sourceIsRelatableToTargetInEnclosingTypes (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:39611:25)
  at PullTypeResolver.sourcePropertyIsRelatableToTargetProperty (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:39935:66)
  at PullTypeResolver.sourcePropertyIsAssignableToTargetProperty (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:39554:69)
  at PullTypeResolver.typeCheckIfTypeExtendsType (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:41369:45)
  at /Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:41507:34
  at Function.PullTypeResolver.typeCheck (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:40589:21)
  at TypeScriptCompiler.getSemanticDiagnostics (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:45510:41)
  at CompilerIterator.moveNextSemanticsPhase (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:46021:45)
  at CompilerIterator.moveNextInternal (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:45981:33)
  at CompilerIterator.moveNext (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/node_modules/typescript/bin/tsc-unlocked.js:45961:25)
  at BatchCompiler._compile (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/tsc.js:125:16)
  at BatchCompiler._batchCompile (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/tsc.js:103:18)
  at /Users/gozala/Projects/immutable-js/node_modules/ts-compiler/tsc.js:59:19
  at setupArguments (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/tsc.js:82:13)
  at BatchCompiler.compile (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/tsc.js:57:9)
  at Object.compile (/Users/gozala/Projects/immutable-js/node_modules/ts-compiler/tsc.js:12:32)
  at Object.module.exports.process (/Users/gozala/Projects/immutable-js/resources/jestPreprocessor.js:9:10)
  at Object.readAndPreprocessFileContent (/Users/gozala/Projects/immutable-js/node_modules/jest-cli/src/lib/utils.js:332:53)
  at Loader._execModule (/Users/gozala/Projects/immutable-js/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:214:11)
  at Loader.requireModule (/Users/gozala/Projects/immutable-js/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:916:12)
  at jasmineTestRunner (/Users/gozala/Projects/immutable-js/node_modules/jest-cli/src/jasmineTestRunner/jasmineTestRunner.js:242:16)
  at /Users/gozala/Projects/immutable-js/node_modules/jest-cli/src/TestRunner.js:371:12
  at _fulfilled (/Users/gozala/Projects/immutable-js/node_modules/jest-cli/node_modules/q/q.js:798:54)
  at self.promiseDispatch.done (/Users/gozala/Projects/immutable-js/node_modules/jest-cli/node_modules/q/q.js:827:30)
  at Promise.promise.promiseDispatch (/Users/gozala/Projects/immutable-js/node_modules/jest-cli/node_modules/q/q.js:760:13)
  at /Users/gozala/Projects/immutable-js/node_modules/jest-cli/node_modules/q/q.js:574:44
  at flush (/Users/gozala/Projects/immutable-js/node_modules/jest-cli/node_modules/q/q.js:108:17)
  at /Users/gozala/Projects/immutable-js/node_modules/jest-cli/src/lib/FakeTimers.js:325:7
  at process._tickCallback (node.js:355:11)
```

**Comment by leebyron** [comment]
Just reworked the test runner to no longer used the tsc wrapper but use typescript services directly. It should be both faster to run tests and hopefully not fail like this.

If you pull and run `npm update` you should get the latest dev dependencies which should hopefully fix the issue. If it doesn't, re-open it, and we will look into what's wrong with Typescript so you can file an issue on them.

**Comment by Gozala** [comment]
This is strange `npm update` did not resolved it although just deleting `node_moudles` and then `npm install` worked. Although I do see one test failing:

```sh
 FAIL  __tests__/Map.ts (8.453s)
● Map › it does not accept strings (iterable, but scalar)
  - Expected function to throw Expected Array or iterable object of [k, v] entries, or keyed object: abc , but it threw Expected [K, V] tuple: a
        at Spec.<anonymous> (/Users/gozala/Projects/immutable-js/__tests__/Map.ts:63:12)
```

**Comment by leebyron** [comment]
Strange. CI claims all tests pass. I'll look into it.
