### ISSUE TITLE
Using Immutable.List in getInitialState throws iterable.length warning

### ISSUE THREAD

**Issue by bunkat** [facebook/immutable-js#471]
I'm doing the following in my component where ProjectStore.projects() returns an Immutable.List (React 13.3).

````
  getInitialState() {
    return {
      projects: ProjectStore.projects()
    }
  }
````

However, I get the following `iterable.length has been deprecated` warning.  If I comment out that function, the warning disappears.

````
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at List.Object.defineProperty.get (eval at <anonymous> (http://192.168.1.106:8080/app.js:2542:2), <anonymous>:4584:21)
    at eval (eval at <anonymous> (http://192.168.1.106:8080/app.js:3436:2), <anonymous>:10:47)
    at isArrayLike (eval at <anonymous> (http://192.168.1.106:8080/app.js:3064:2), <anonymous>:12:36)
    at baseMergeDeep (eval at <anonymous> (http://192.168.1.106:8080/app.js:3052:2), <anonymous>:40:9)
    at eval (eval at <anonymous> (http://192.168.1.106:8080/app.js:2812:2), <anonymous>:46:42)
    at arrayEach (eval at <anonymous> (http://192.168.1.106:8080/app.js:3046:2), <anonymous>:15:9)
    at baseMerge (eval at <anonymous> (http://192.168.1.106:8080/app.js:2812:2), <anonymous>:38:22)
    at eval (eval at <anonymous> (http://192.168.1.106:8080/app.js:2818:2), <anonymous>:37:9)
    at eval (eval at <anonymous> (http://192.168.1.106:8080/app.js:2914:2), <anonymous>:45:27)
    at newConfig.getInitialState (eval at <anonymous> (http://192.168.1.106:8080/app.js:2176:2), <anonymous>:13:14)
````

What's the current correct method of using Immutable.js with component state?

**Comment by leebyron** [comment]
Certainly nothing about the code you've posted here is incorrect. From your stack trace it looks like your application is treating the Immutable `List` as an array somewhere - see `arrayEach` and `baseMerge` which are not part of React or Immutable's codebases.
