### ISSUE TITLE
Reducing and concating an empty list returns undefined

### ISSUE THREAD

**Issue by csaintc** [facebook/immutable-js#770]
Example code:
```
new Immutable.List().reduce((left, right)=>left.concat(right));

undefined
```

**Comment by pandanoir** [comment]
document says "if initialReduction is not provided, or is null, the first item in the Iterable will be used." So this behavior is native, isn't this?

**Comment by leebyron** [comment]
Native behavior is to throw an error, which is at least more descriptive.

```js
> [].reduce((left, right)=>left.concat(right));
TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at repl:1:4
    at REPLServer.defaultEval (repl.js:260:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:429:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
```
