### ISSUE TITLE
Update to Jest >=0.5.0 so tests can run on Node 4.x

### ISSUE THREAD

**Issue by thomasboyt** [facebook/immutable-js#783]
Jest 0.4.x only works on Node 0.12.x and below, so Immutable JS tests can't be run on newer versions of Node.

I started looking into this, and found that while Jest 0.5.x works fine, 0.6.0  and above breaks various tests:

```
$ npm test

> immutable@3.7.6 test /Users/tboyt/Coding/immutable-js
> ./resources/node_test.sh

Using Jest CLI v0.8.2, jasmine1
 PASS  __tests__/updateIn.ts (0.814s)
 PASS  __tests__/Set.ts (0.181s)
 PASS  __tests__/IterableSeq.ts (0.134s)
 PASS  __tests__/slice.ts (2.206s)
Running 31 test suites.../Users/tboyt/Coding/immutable-js/contrib/cursor/__tests__/Cursor.ts 7:24 Exported external package typings file '/Users/tboyt/Coding/immutable-js/node_modules/immutable/contrib/cursor/index.d.ts' is not a module. Please contact the package author to update the package definition.
 FAIL  contrib/cursor/__tests__/Cursor.ts
● Runtime Error
Error: Compiling /Users/tboyt/Coding/immutable-js/contrib/cursor/__tests__/Cursor.ts failed
    at compileTypeScript (/Users/tboyt/Coding/immutable-js/resources/jestPreprocessor.js:61:9)
    at Object.module.exports.process (/Users/tboyt/Coding/immutable-js/resources/jestPreprocessor.js:74:43)
    at module.exports.config.scriptPreprocessor.config.preprocessorIgnorePatterns.some (/Users/tboyt/Coding/immutable-js/node_modules/jest-cli/src/lib/transform.js:133:33)
    at Loader._execModule (/Users/tboyt/Coding/immutable-js/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:176:25)
    at Loader.requireModule (/Users/tboyt/Coding/immutable-js/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:760:14)
    at jasmine1 (/Users/tboyt/Coding/immutable-js/node_modules/jest-cli/src/testRunners/jasmine/jasmine1.js:233:16)
    at /Users/tboyt/Coding/immutable-js/node_modules/jest-cli/src/TestRunner.js:261:14
 PASS  __tests__/Range.ts (0.399s)
 FAIL  __tests__/concat.ts (1.859s)
● concat › it concats arrays to indexed seq
  - Expected: {
    | 0: 1,
    | 1: 2,
    | 2: 3,
    | 3: 4,
    | 4: 5,
    | 5: 6
    } toEqual: {
    | 0: 1,
    | 1: 2,
    | 2: 3,
    | 3: 4,
    | 4: 5,
    | 5: 6
    }
        at Spec.eval (__tests__/concat.ts:43:40)
● concat › it concats values
  - Expected: {
    | 0: 1,
    | 1: 2,
    | 2: 3,
    | 3: 4,
    | 4: 5,
    | 5: 6
    } toEqual: {
    | 0: 1,
    | 1: 2,
    | 2: 3,
    | 3: 4,
    | 4: 5,
    | 5: 6
    }
        at Spec.eval (__tests__/concat.ts:48:46)
● concat › it concats multiple arguments
  - Expected: {
    | 0: 1,
    | 1: 2,
    | 2: 3,
    | 3: 4,
    | 4: 5,
    | 5: 6,
    | 6: 7,
    | 7: 8,
    | 8: 9
    } toEqual: {
    | 0: 1,
    | 1: 2,
    | 2: 3,
    | 3: 4,
    | 4: 5,
    | 5: 6,
    | 6: 7,
    | 7: 8,
    | 8: 9
    }
        at Spec.eval (__tests__/concat.ts:63:43)
● concat › it can concat itself!
  - Expected: {
    | 0: 1,
    | 1: 2,
    | 2: 3,
    | 3: 1,
    | 4: 2,
    | 5: 3,
    | 6: 1,
    | 7: 2,
    | 8: 3
    } toEqual: {
    | 0: 1,
    | 1: 2,
    | 2: 3,
    | 3: 1,
    | 4: 2,
    | 5: 3,
    | 6: 1,
    | 7: 2,
    | 8: 3
    }
        at Spec.eval (__tests__/concat.ts:68:43)
 PASS  __tests__/Stack.ts (2.413s)
 PASS  __tests__/merge.ts (0.085s)
 PASS  __tests__/List.ts (6.508s)
 PASS  __tests__/flatten.ts (0.264s)
 PASS  __tests__/Map.ts (7.944s)
 FAIL  __tests__/ArraySeq.ts (0.096s)
● ArraySequence › it maps
  - Expected: {
    | 0: 2,
    | 1: 4,
    | 2: 6
    } toEqual: {
    | 0: 2,
    | 1: 4,
    | 2: 6
    }
        at Spec.eval (__tests__/ArraySeq.ts:21:19)
 PASS  __tests__/OrderedMap.ts (0.033s)
 PASS  __tests__/Seq.ts (0.027s)
 PASS  __tests__/Record.ts (0.026s)
 PASS  __tests__/zip.ts (0.766s)
 PASS  __tests__/count.ts (0.029s)
 PASS  __tests__/Equality.ts (3.248s)
 PASS  __tests__/MultiRequire.js (0.11s)
 FAIL  __tests__/groupBy.ts (0.038s)
● groupBy › it groups indexed sequences, maintaining indicies
  - Expected: {
    | 0: {
    | | 1: 2,
    | | 3: 4,
    | | 5: 6
    | },
    | 1: {
    | | 0: 1,
    | | 2: 3,
    | | 4: 5
    | }
    } toEqual: {
    | 0: {
    | | 1: 2,
    | | 3: 4,
    | | 5: 6
    | },
    | 1: {
    | | 0: 1,
    | | 2: 3,
    | | 4: 5
    | }
    }
        at Spec.eval (__tests__/groupBy.ts:19:114)
 PASS  __tests__/ObjectSeq.ts (0.024s)
 PASS  __tests__/OrderedSet.ts (0.029s)
 PASS  __tests__/ListJS.js (0.07s)
 PASS  __tests__/Conversion.ts (4.134s)
 PASS  __tests__/RecordJS.js (0.153s)
 PASS  __tests__/get.ts (0.021s)
 PASS  __tests__/sort.ts (0.031s)
 PASS  __tests__/interpose.ts (0.02s)
 PASS  __tests__/IndexedSeq.ts (0.043s)
 PASS  __tests__/KeyedSeq.ts (1.305s)
 PASS  __tests__/Repeat.ts (0.024s)
 PASS  __tests__/splice.ts (1.375s)
 PASS  __tests__/minmax.ts (5.137s)
 PASS  __tests__/join.ts (3.348s)
6 tests failed, 1 test suite failed, 427 tests passed (433 total in 35 test suites, run time 15.815s)
npm ERR! Test failed.  See above for more details.
```

It looks like Jest is transforming the objects it's trying to assert in an unexpected way, since the pretty-printed objects in don't match up to what's actually being tested.

Of course, the easy fix to is to just use Jest `0.5.x` (which is what I'm doing so I can test without installing nvm and setting up Node 0.12), but long-term it might be better to make sure this works with current versions of Jest.

**Comment by leebyron** [comment]
Thanks for your investigation. Agreed being stuck on old node sucked.
