### ISSUE TITLE
Accessing `Map` values crashes React app, even after `.toJS()`

### ISSUE THREAD

**Issue by brandonmp** [facebook/immutable-js#947]
Packages: Redux (3.0.0), React (15.2.0), React-Redux (4.0.0), and Immutable (3.8.1)
### What happened

When trying to access any methods on an `Immutable.Map` that's been passed down via `Props` from my Redux store, my app crashes.  I'm using `hot-reloader`, and as soon as it re-builds, my console spits out 2 warnings and an error:  

```
warning.js:44 Warning: There is an internal error in the React performance measurement code. Did not expect componentDidMount timer to start while render timer is still in progress for another instance.warning @ warning.js:44beginLifeCycleTimer @ ReactDebugTool.js:110onBeginLifeCycleTimer @ ReactDebugTool.js:221invokeComponentDidMountWithTimer @ ReactCompositeComponent.js:58notifyAll @ CallbackQueue.js:67close @ ReactReconcileTransaction.js:81closeAll @ Transaction.js:204perform @ Transaction.js:146perform @ Transaction.js:138perform @ ReactUpdates.js:90flushBatchedUpdates @ ReactUpdates.js:173closeAll @ Transaction.js:204perform @ Transaction.js:151batchedUpdates @ ReactDefaultBatchingStrategy.js:63enqueueUpdate @ ReactUpdates.js:201enqueueUpdate @ ReactUpdateQueue.js:25enqueueElementInternal @ ReactUpdateQueue.js:217(anonymous function) @ ReactMount.js:253scrollMonitor @ ReactMount.js:241_updateRootComponent @ ReactMount.js:252_renderSubtreeIntoContainer @ ReactMount.js:344render @ ReactMount.js:392render @ main.js:48render @ main.js:70(anonymous function) @ main.js:75hotApply @ bootstrap ad5d90a…:518cb @ process-update.js:52hotUpdateDownloaded @ bootstrap ad5d90a…:334hotAddUpdateChunk @ bootstrap ad5d90a…:306webpackHotUpdateCallback @ bootstrap ad5d90a…:27(anonymous function) @ 0.2552c86….hot-update.js:1
```

```
warning.js:44 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).warning @ warning.js:44createElement @ ReactElementValidator.js:166renderError @ main.js:66render @ main.js:72(anonymous function) @ main.js:75hotApply @ bootstrap ad5d90a…:518cb @ process-update.js:52hotUpdateDownloaded @ bootstrap ad5d90a…:334hotAddUpdateChunk @ bootstrap ad5d90a…:306webpackHotUpdateCallback @ bootstrap ad5d90a…:27(anonymous function) @ 0.2552c86….hot-update.js:1
process-update.js:115 [HMR] Cannot check for update (Full reload needed)
process-update.js:116 [HMR] Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at invariant (http://192.168.8.101:3000/vendor.ad5d90acbf535202d2ce.js:1393:16)
    at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (http://192.168.8.101:3000/app.ad5d90acbf535202d2ce.js:19109:103)
    at ReactCompositeComponentWrapper.performInitialMount (http://192.168.8.101:3000/app.ad5d90acbf535202d2ce.js:19562:23)
    at ReactCompositeComponentWrapper.mountComponent (http://192.168.8.101:3000/app.ad5d90acbf535202d2ce.js:19436:22)
    at Object.mountComponent (http://192.168.8.101:3000/app.ad5d90acbf535202d2ce.js:11586:36)
    at mountComponentIntoNode (http://192.168.8.101:3000/app.ad5d90acbf535202d2ce.js:24688:33)
    at ReactReconcileTransaction.perform (http://192.168.8.101:3000/app.ad5d90acbf535202d2ce.js:12607:21)
    at batchedMountComponentIntoNode (http://192.168.8.101:3000/app.ad5d90acbf535202d2ce.js:24709:16)
    at ReactDefaultBatchingStrategyTransaction.perform (http://192.168.8.101:3000/app.ad5d90acbf535202d2ce.js:12607:21)
    at Object.batchedUpdates (http://192.168.8.101:3000/app.ad5d90acbf535202d2ce.js:21773:20)

```

`Uncaught TypeError: Cannot read property '__reactInternalInstance$4heywo6qdln2sth55h7inyu8fr' of nullgetClosestInstanceFromNode @ ReactDOMComponentTree.js:107findParent @ ReactEventListener.js:39handleTopLevelImpl @ ReactEventListener.js:68perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:98dispatchEvent @ ReactEventListener.js:150`

After that, reloading yields the following warnings/errors:

```
Warning: There is an internal error in the React performance measurement code. Did not expect componentDidUpdate timer to start while render timer is still in progress for another instance.warning @ warning.js:44beginLifeCycleTimer @ ReactDebugTool.js:110onBeginLifeCycleTimer @ ReactDebugTool.js:221invokeComponentDidUpdateWithTimer @ ReactCompositeComponent.js:69notifyAll @ CallbackQueue.js:67close @ ReactReconcileTransaction.js:81closeAll @ Transaction.js:204perform @ Transaction.js:146perform @ Transaction.js:138perform @ ReactUpdates.js:90flushBatchedUpdates @ ReactUpdates.js:173closeAll @ Transaction.js:204perform @ Transaction.js:151batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:98_renderNewRootComponent @ ReactMount.js:285_renderSubtreeIntoContainer @ ReactMount.js:371render @ ReactMount.js:392render @ main.js:48render @ main.js:70(anonymous function) @ main.js:81__webpack_require__ @ bootstrap aa97362…:585fn @ bootstrap aa97362…:109(anonymous function) @ app.aa97362….js:6__webpack_require__ @ bootstrap aa97362…:585webpackJsonpCallback @ bootstrap aa97362…:21(anonymous function) @ app.aa97362….js:1
warning.js:44Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).warning @ warning.js:44createElement @ ReactElementValidator.js:166renderError @ main.js:66render @ main.js:72(anonymous function) @ main.js:81__webpack_require__ @ bootstrap aa97362…:585fn @ bootstrap aa97362…:109(anonymous function) @ app.aa97362….js:6__webpack_require__ @ bootstrap aa97362…:585webpackJsonpCallback @ bootstrap aa97362…:21(anonymous function) @ app.aa97362….js:1
invariant.js:38Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.invariant @ invariant.js:38instantiateReactComponent @ instantiateReactComponent.js:86performInitialMount @ ReactCompositeComponent.js:388mountComponent @ ReactCompositeComponent.js:262mountComponent @ ReactReconciler.js:47mountComponentIntoNode @ ReactMount.js:105perform @ Transaction.js:138batchedMountComponentIntoNode @ ReactMount.js:126perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:98_renderNewRootComponent @ ReactMount.js:285_renderSubtreeIntoContainer @ ReactMount.js:371render @ ReactMount.js:392renderError @ main.js:66render @ main.js:72(anonymous function) @ main.js:81__webpack_require__ @ bootstrap aa97362…:585fn @ bootstrap aa97362…:109(anonymous function) @ app.aa97362….js:6__webpack_require__ @ bootstrap aa97362…:585webpackJsonpCallback @ bootstrap aa97362…:21(anonymous function) @ app.aa97362….js:1
invariant.js:38Uncaught Invariant Violation: React DOM tree root should always have a node reference.invariant @ invariant.js:38getNodeFromInstance @ ReactDOMComponentTree.js:166findParent @ ReactEventListener.js:37handleTopLevelImpl @ ReactEventListener.js:68perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:98dispatchEvent @ ReactEventListener.js:150
```

Any context in which I try to access a method creates this error, e.g., in a `console.log(Map.get('key'))`, or assigning a component prop to `Map.get('key')`.  

However, `console.log(Map)` works fine, and the console indicates that it's a regular `Immutable.js` map. 

What's even more bizarre, I think, is that the error happens even if I try the following:
1. invoke `.toJS()` and try to access the object properties via normal JS. Interestingly, no matter where in the chain from reducer to `console.log()` I do this, it still has the same result.
2. Assign each property to a new JS object. eg, 

```
let tempObj = {
propA: Map.get('propA'),
propB: Map.get('propB'),
}
```

On doing this, `console.log(tempObj.propA)` crashes in the same fashion.
### How to reproduce

I wish I could be of more help here, but I'm absolutely stumped at why this is happening or how to reproduce it in isolation.  

[I cloned my repo and added some detailed notes](https://github.com/brandonmp/immutable_bug) to the `readme`, and I'm happy to discuss w/ anyone that's interested.

The issue happened in a totally different part of the project the other day. I was able to code around it, but this time I figured it wasn't just a fluke.

**Comment by brandonmp** [comment]
I've done some more tinkering/weeping w/ this. I was able to fix it for my purposes. 

I had the component structured like this (pseudocode): 

````
this.state={modalBody: null, isModalOpen: false}

// sets content to the state, which is passed via props to Modal 
handleClick(modalText)={this.setState({isModalOpen: true, modalBody: modalText})

// List render method
Immutable.List.map((item) => {
  <CustomListItem item={item} modalOpener={this.handleClick}  />
}

<Modal content={this.state.modalBody} open={this.state.isModalOpen} />

// <ListIitem>
_clickHandle() {
  this.props.modalOpener(this.props.item)
}

render() {
<ListItem 
  onTouchTap={this.clickHandle}
  primaryText={this.props.item.get('text')}
/>
}
````
^^(which is a pattern i got from an `eslint plugin` doc. Note that to avoid creating an instance of the click handler and dialog for each item generated by `.map()`, I've created an intermediate component. 

I **think** the problem lies in the fact that I was passing the `item` generated by `map()` outside of the `map()` anonymous function, but I've been unable to confirm this theory. 


However, when I changed it to something like this:


````
this.state={modalBody: null, isModalOpen: false}

// sets content to the state, which is passed via props to Modal 
handleClick(modalText)={this.setState({isModalOpen: true, modalBody: modalText})

// List render method
Immutable.List.map((item) => {
  <CustomListItem 
    item={item} 
    modalOpener={() => {this.handleClick(item.get('text')}}  
  />

<Modal content={this.state.modalBody} open={this.state.isModalOpen} />
}
````

...things work ostensibly fine. This is obviously not optimal as it's generating a `<Modal>` for every list  item (vice creating one just for the clicked list item), but it's working for now.


The other things I tried:

1. `forEach()` instead of `map()`. I thought maybe it had something to do w/ side effects, but no dice.
2. `connect()`-ing the `<Modal>` component itself to the `Redux store`, then just passing an ID string from the `.map()` function. Unfortunately this also crashed (just as before, I even tried creating a brand new `string` object to sever the tie to the original data structure, but nothin'-doin'.

**Comment by leebyron** [comment]
Closing this aging issue - sorry I hope you were able to figure out what was going wrong with your app. If you found something related to Immutable.js in there, please open another specific issue
