### ISSUE TITLE
"_name" is not usable as a key in Record classes, and it is not documented

### ISSUE THREAD

**Issue by yavuzmester** [facebook/immutable-js#970]
```
var ABRecord = new Immutable.Record({_name:null})
var myRecord = new ABRecord({_name:"Bob"})
```

Above code gives **Uncaught Error: Cannot set on an immutable record.**

It seems that "_name" is reserved to Record and can not be used as a key. This is not documented.

**Comment by nickretallack** [comment]
Did this ever get documented?  I'm seeing a similar problem but for `name` without the underscore now.

```
$ node --version
v8.4.0
$ node
> const {Record} = require('immutable-js')
undefined
> const A = new Record({name: ''})
undefined
> const a = new A({name: 'bob'})
Error: Can't call set on an immutable record.
    at invariant (/Users/nick/Documents/GitHub/Turbo/node_modules/immutable-js/dist/immutable.js:182:29)
    at Record.set (/Users/nick/Documents/GitHub/Turbo/node_modules/immutable-js/dist/immutable.js:1360:15)
    at new Record (/Users/nick/Documents/GitHub/Turbo/node_modules/immutable-js/dist/immutable.js:1261:44)
    at repl:1:11
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
```

**Comment by nickretallack** [comment]
Oops.  I was using `immutable-js` instead of `immutable`.
